POST http://localhost:5000/login
Content-Type: application/json

{
    "username": "duong.tranvan@mobifone.vn",
    "password": "Conchomuc2010"
}
####
POST http://10.25.8.38:5000/login

Content-Type: application/json

{
    "username": "duong.tranvan@mobifone.vn",
    "password": "Conchomuc2010"
}

###

GET http://localhost:5000/dashboard/dashboard-view-count
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiZHVvbmcudHJhbnZhbkBtb2JpZm9uZS52biIsImlhdCI6MTcwMzczMTU4NH0.wwb2bqcPOPzYmFCtKQkuNx27Y8rzqJevMv0PqjTVbxI